### ISSUE TITLE
Can't intercept connection status codes

### ISSUE THREAD

**Issue by hielkehoeve** [fernandezpablo85/scribe-java#544] opened 2015-03-11 15:26 UTC
I would like to tell my users what is going wrong when they are trying to login into my Android app whilst the application my app is communicating to is offline. The problem is that my app can't see whats going wrong either because the response is kept secret.

The resulting statuscode is 503, however there is no way to get to the response. OAuth10aServiceImpl#getRequestToken() does have it but never uses it... All I can get is the content the application (or its loadbalancer) is returning.

```
org.scribe.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: 'The specified page is not available right now. Try again later.'
            at org.scribe.extractors.TokenExtractorImpl.extract(TokenExtractorImpl.java:41)
            at org.scribe.extractors.TokenExtractorImpl.extract(TokenExtractorImpl.java:27)
            at org.scribe.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:64)
            at org.scribe.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:40)
            at org.scribe.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:45)
```

**Comment by fernandezpablo85** [comment] 2015-03-19 00:18
I was wondering wether to include the response code or even the response object itself in the exception but that would have to be nullable since there are other `OAuthException`s that are not generated because of a failed http request.

Another option would be to throw a different (subclass) exception on http errors that includes the response. @hielkehoeve  What do you think?

**Comment by hielkehoeve** [comment] 2015-06-04 08:42
Apologies for the late response, I seem to have notifications disabled. Enabled for this issue.

The location where the Exception is thrown is very isolated so you'd have to let it throw a subclass of OAuthException, catch it in OAuth10aServiceImpl and throw another subclass of OAuthException in order to provide users access to the response/response code.

I was thinking about replacing the RequestTuner with a listener which can do more than some very limited tuning. (like adding headers before adding a body). What do you think?

**Comment by fernandezpablo85** [comment] 2015-06-04 16:25
Sure, sounds OK. if you send a PR I'd be glad to review it. Please send one PR for each thing (improved tuner, exception handling).

**Comment by fernandezpablo85** [comment] 2015-07-29 15:35
Closing (but waiting for the PR)

**Closed by fernandezpablo85** 2015-07-29 15:35 UTC

**Comment by ubuntudroid** [comment] 2017-03-28 12:31
@hielkehoeve @fernandezpablo85 Has this been implemented since? I am struggling with the same problem now.

**Comment by kullfar** [comment] 2017-03-28 13:11
Are you using the latest ScribeJava v4? It has changed a lot

**Comment by ubuntudroid** [comment] 2017-03-28 14:51
@kullfar I am.

**Comment by kullfar** [comment] 2017-03-28 15:07
You have another problem than ;-)
pls create new issue in case you have any problems with the current version of the ScribeJava

**Comment by ubuntudroid** [comment] 2017-03-28 17:09
Well, the problem is exactly the same because there is still no response
code available when requesting a request/access token. Shall I create a new
ticket anyway, or do you want to reopen this one as the aforementioned PR
apparently has never been created?

Stas Gromov <notifications@github.com> schrieb am Di., 28. März 2017, 17:07:

**Comment by kullfar** [comment] 2017-03-29 09:29
Do you need response http code? Or OAuth error?
For example there is such class
https://github.com/scribejava/scribejava/blob/master/scribejava-core/src/main/java/com/github/scribejava/core/model/OAuth2AccessTokenErrorResponse.java

you will get it in case of error for default OAuth2 service while requesting AccessToken.

ps. Sure, we can add response code to the exceptions and/or oauth errors. PullRequest will be the best solution, because I don't know what exactly is your need. Or Issue with the example with the current version of ScribeJava.

Thanks!

**Comment by ubuntudroid** [comment] 2017-03-29 13:31
Is there also something like that for the response token? And I'm using OAuth10a, there doesn't seem to be something similar. I'll create a new issue with my exact requirements later. Maybe I can even come up with a PR in the upcoming weeks.

**Comment by kullfar** [comment] 2017-03-30 07:53
Yep. it's implemented only for OAuth2. OAuth2AccessTokenErrorResponse was the single need for the moment.

**Comment by ubuntudroid** [comment] 2017-04-01 10:17
After trying to get to work scribe with our own API I've decided to not go with scribe. This is not scribe's fault, but because of how OAuth is implemented in our API. It sports considerable changes to the standard - that's why I asked you about possibilities to get more response information. But in the end I realized, that trying to bend scribe to our APIs will doesn't make any sense because scribe clearly states that it adheres to OAuth standards while our API doesn't. So I'll just implement our OAuth'ish auth handling from scratch.

**Comment by kullfar** [comment] 2017-04-04 08:59
ScribeJava attempts to support nonstandard APIs in their custom XXXAPIService.java implementations. 
Like here https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/main/java/com/github/scribejava/apis/service
And providing HTTP response code in XXXResponse.java is not describe in OAuth specs, it can be implemented in case of needs.
